[package]
name = "icns"
version = "0.1.0"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

[lib]
name = "icns"
path = "src/lib.rs"

[[bin]]
name = "icnsify"
path = "src/main.rs"

[dependencies]
image = "0.20.1"
byteorder = "1.2.7"
rayon = "1.0.3"
clap = "2.32.0"

[dev-dependencies]
clap = "2.32.0"
num-complex = "0.2"