[package]
name = "icns"
version = "0.1.0"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
byteorder = "1.2.7"
rayon = "1.0.3"

[dev-dependencies]
clap = "2.32.0"